#include "filesystem_service.h"
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QStandardPaths>
#include <QTextStream>
#include <QUrl>

static bool copyRecursive(const QString &from,const QString &to){QFileInfo source(from);if(source.isDir()){if(!QDir().mkpath(to))return false;for(const auto &child:QDir(from).entryInfoList(QDir::AllEntries|QDir::NoDotAndDotDot|QDir::Hidden))if(!copyRecursive(child.absoluteFilePath(),QDir(to).filePath(child.fileName())))return false;return true;}return QFile::copy(from,to);}
QVariantList FilesystemService::list(const QString &path,bool includeHidden)const{QVariantList out;QDir d(path);if(!d.exists())return out;auto flags=QDir::AllEntries|QDir::NoDotAndDotDot|QDir::System;if(includeHidden)flags|=QDir::Hidden;for(const auto &i:d.entryInfoList(flags,QDir::DirsFirst|QDir::Name))out<<QVariantMap{{"name",i.fileName()},{"path",i.absoluteFilePath()},{"directory",i.isDir()},{"size",i.isDir()?0:i.size()},{"modified",i.lastModified()},{"permissions",int(i.permissions())},{"hidden",i.isHidden()}};return out;}
QVariantList FilesystemService::trashList()const{QVariantList out;const QString home=QStandardPaths::writableLocation(QStandardPaths::HomeLocation),dir=home+"/.local/share/Trash/files";QDir d(dir);for(const auto &i:d.entryInfoList(QDir::AllEntries|QDir::NoDotAndDotDot|QDir::Hidden,QDir::Name))out<<QVariantMap{{"name",i.fileName()},{"path",i.absoluteFilePath()},{"directory",i.isDir()},{"size",i.isDir()?0:i.size()},{"modified",i.lastModified()}};return out;}
bool FilesystemService::createDirectory(const QString &path)const{return QDir().mkpath(path);}
bool FilesystemService::createFile(const QString &path)const{QFile f(path);if(!f.open(QIODevice::WriteOnly))return false;f.close();return true;}
bool FilesystemService::removePath(const QString &path)const{QFileInfo i(path);if(!i.exists())return false;return i.isDir()?QDir(path).removeRecursively():QFile::remove(path);}
bool FilesystemService::renamePath(const QString &from,const QString &to)const{return QFile::rename(from,to);}
bool FilesystemService::copyPath(const QString &from,const QString &to)const{return copyRecursive(from,to);}
bool FilesystemService::movePath(const QString &from,const QString &to)const{return QFile::rename(from,to)||(copyRecursive(from,to)&&removePath(from));}
bool FilesystemService::trashPath(const QString &path)const{QFileInfo info(path);if(!info.exists())return false;const QString home=QStandardPaths::writableLocation(QStandardPaths::HomeLocation),filesDir=home+"/.local/share/Trash/files",infoDir=home+"/.local/share/Trash/info";if(!QDir().mkpath(filesDir)||!QDir().mkpath(infoDir))return false;const QString base=info.fileName();QString target=filesDir+"/"+base;int n=1;while(QFileInfo::exists(target))target=filesDir+"/"+base+"."+QString::number(n++);QFile meta(infoDir+"/"+QFileInfo(target).fileName()+".trashinfo");if(!meta.open(QIODevice::WriteOnly|QIODevice::Text))return false;QTextStream s(&meta);s<<"[Trash Info]\nPath="<<info.absoluteFilePath()<<"\nDeletionDate="<<QDateTime::currentDateTime().toString(Qt::ISODate)<<"\n";if(!movePath(path,target))return false;meta.close();return true;}
bool FilesystemService::restoreTrash(const QString &trashName)const{const QString home=QStandardPaths::writableLocation(QStandardPaths::HomeLocation),filesDir=home+"/.local/share/Trash/files",infoDir=home+"/.local/share/Trash/info";QFile meta(infoDir+"/"+trashName+".trashinfo");if(!meta.open(QIODevice::ReadOnly|QIODevice::Text))return false;QString original;while(!meta.atEnd()){const QString line=QString::fromUtf8(meta.readLine()).trimmed();if(line.startsWith("Path=")){original=line.mid(5);break;}}if(original.isEmpty())return false;const QString trashed=filesDir+"/"+trashName;if(!QFileInfo::exists(trashed))return false;QFileInfo dest(original);if(dest.exists()){const QString dir=dest.absolutePath(),base=dest.fileName();int n=1;original=dir+"/"+base+"."+QString::number(n++);while(QFileInfo::exists(original))original=dir+"/"+base+"."+QString::number(n++);}if(!QDir().mkpath(QFileInfo(original).absolutePath()))return false;if(!movePath(trashed,original))return false;meta.remove();return true;}
bool FilesystemService::deleteTrash(const QString &trashName)const{const QString home=QStandardPaths::writableLocation(QStandardPaths::HomeLocation);QFile meta(home+"/.local/share/Trash/info/"+trashName+".trashinfo");const bool ok=removePath(home+"/.local/share/Trash/files/"+trashName);meta.remove();return ok;}
bool FilesystemService::openPath(const QString &path)const{if(!QFileInfo::exists(path))return false;const QString url=QUrl::fromLocalFile(QFileInfo(path).absoluteFilePath()).toString();return QProcess::startDetached(QStringLiteral("xdg-open"),QStringList{url});}
